#     Copyright 2024, MCSL Team, mailto:services@mcsl.com.cn
#
#     Part of "MCSL2", a simple and multifunctional Minecraft server launcher.
#
#     Licensed under the GNU General Public License, Version 3.0, with our
#     additional agreements. (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#        https://github.com/MCSLTeam/MCSL2/raw/master/LICENSE
#
################################################################################
name: Windows Debug Build

on: workflow_dispatch

jobs:
  Windows:
    runs-on: windows-2019
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: |
            requirement.txt

      - name: Dependencies
        shell: pwsh
        run: |
          python -m pip install tomli
          python Tools/gen-requirements.py
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python -m pip uninstall numpy -y
          python -m pip uninstall scipy -y

      - name: Build
        run: |
          python -m lndl_nuitka . -y

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MCSL2-Windows-x64
          path: |
            build/MCSL2.dist/**/*
